name: MyPurpurPlugin
main: org.example.MyPurpurPlugin
version: 1.0
api-version: 1.21
author: Oleg
description: Плагин для управления командами

commands:
  team:
    description: Управление командами (создание, вступление, выход, и т.д.)
    usage: /team <create | join | leave | list | members | help> [аргументы]
    aliases: [t]
    permission: mypurpurplugin.team
    permission-message: "❌ У вас нет прав для использования этой команды!"

  teamadmin:
    description: Управление командами для лидеров (передача лидерства, исключение, роспуск, и т.д.)
    usage: /teamadmin <transfer | kick | disband | rename | setprefix | setcolor | help> [аргументы]
    aliases: [ta]
    permission: mypurpurplugin.teamadmin
    permission-message: "❌ У вас нет прав для использования этой команды!"

  getteamsuuidlist:
    description: Показывает список команд и их UUID (только для OP)
    usage: /<command>
    permission: mypurpurplugin.getteamsuuidlist
    permission-message: "❌ У вас нет прав для использования этой команды!"

  getteamuuid:
    description: Показывает UUID команды по названию (только для OP)
    usage: /<command> <название>
    permission: mypurpurplugin.getteamuuid
    permission-message: "❌ У вас нет прав для использования этой команды!"

  teamreload:
    description: Перезагрузить конфигурацию плагина (только для консоли)
    usage: /teamreload
    permission: mypurpurplugin.teamreload
    permission-message: "❌ У вас нет прав для использования этой команды!"

  cfgdefault:
    description: Сбросить конфигурацию плагина до дефолтных настроек (только для консоли)
    usage: /cfgdefault
    permission: mypurpurplugin.cfgdefault
    permission-message: "❌ У вас нет прав для использования этой команды!"

  menu:
    description: Открывает меню
    usage: /menu

  debugtoggle:
    description: Переключить режим отладки (только для консоли)
    usage: /debugtoggle
    permission: mypurpurplugin.debugtoggle
    permission-message: "❌ У вас нет прав для использования этой команды!"

permissions:
  mypurpurplugin.team:
    description: Доступ к команде /team
    default: true
  mypurpurplugin.teamadmin:
    description: Доступ к команде /teamadmin (для лидеров)
    default: true
  mypurpurplugin.admin:
    description: Получает уведомления о действиях с командами
    default: op
  mypurpurplugin.teamreload:
    description: Доступ к команде /teamreload (только для консоли)
    default: op
  mypurpurplugin.cfgdefault:
    description: Доступ к команде /cfgdefault (только для консоли)
    default: op
  mypurpurplugin.debugtoggle:
    description: Доступ к команде /debugtoggle (только для консоли)
    default: op
  mypurpurplugin.getteamsuuidlist:
    description: Доступ к команде /getteamsuuidlist (только для OP)
    default: op
  mypurpurplugin.getteamuuid:
    description: Доступ к команде /getteamuuid (только для OP)
    default: op

